before:

  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{ .Version }} -X main.commit={{ .ShortCommit }}'
    goos:
      - freebsd
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: '{{ .ProjectName }}_v{{ .Version }}'

announce:
  slack:
    enabled: true
    message_template: '📢📢 New Version *{{.Version}}* is released 🎉 🎉\n\nMore detailed changes are <{{ .GitURL }}/blob/{{ .Tag }}/CHANGELOG.md|here>.\nThe provider should already be available to be used directly, but you can manually download the supported plugin at {{ .GitURL }}/releases/tag/{{ .Tag }}\n\n Note: The provider is still `alpha` version'
    channel: '#lapp-cloud-deployments'
    username: 'terraform-provider-sapcc'

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - '--batch'
      - '--local-user'
      - '{{ .Env.GPG_FINGERPRINT }}'
      - '--output'
      - '${signature}'
      - '--detach-sign'
      - '${artifact}'

release:
 draft: false