name: test
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'
jobs:

  test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.16'
          - '1.17'
        terraform:
          - '1.0.3'
          - '1.0.5'
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4

      - name: Prepare Tests
        run: |
          make pull-mock

      - name: Run Acceptance Tests
        timeout-minutes: 10
        env:
          TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}
        run: |
          make testacc